# Basic set up for three package managers
# Documentation -
#   https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "github-actions dependencies"
    commit-message:
      prefix: "gh-actions prod"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "pip dependencies"
    commit-message:
      prefix: "pip prod"
      include: "scope"
